#!/bin/bash
set -e
. /usr/share/debconf/confmodule
db_get authtoken/disable-gnome-keyring-ssh

if [ "$RET" = "true" ]; then
	if [ -e "/etc/xdg/autostart/gnome-keyring-ssh.desktop" ]; then
		md5=`md5sum /etc/xdg/autostart/gnome-keyring-ssh.desktop | awk '{ print $1 }'`
		if [ "${md5}" == "c7572421d45716844d0fca56bd9428bf" ]; then
			TMPFILE=`mktemp`
			cat >> ${TMPFILE} << EOF
@@ -11,4 +11,5 @@
 X-GNOME-Bugzilla-Product=gnome-keyring
 X-GNOME-Bugzilla-Component=general
 X-GNOME-Bugzilla-Version=3.18.3
+X-GNOME-Autostart-enabled=false
 X-Ubuntu-Gettext-Domain=gnome-keyring
EOF
			patch -R /etc/xdg/autostart/gnome-keyring-ssh.desktop < ${TMPFILE} > /dev/null
			rm "${TMPFILE}"
		else
			echo "Unable to restore Gnome Keyring SSH agent"
			echo "Gnome Keyring SSH agent desktop file is not default"
		fi
	else
		echo "Gnome Keyring SSH agent not found"
	fi
fi



db_stop
exit 0
